# Generated by Django 6.0 on 2026-02-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='is_featured',
        ),
    ]
